(() => {
'use strict';
const LOGO=window.TRILHEIROS_LOGO_DATA||'';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function applyBrand(){
  if(LOGO)$$('.brand-logo-mini,.hero-logo,.tracking-logo img,footer img').forEach(img=>{img.src=LOGO;img.removeAttribute('crossorigin');img.style.opacity='1'});
  const title=$('.hero-title');if(title)title.innerHTML='Pra onde vamos<br><span>hoje?</span>';
  let welcome=$('.welcome-kicker');if(!welcome&&title){welcome=document.createElement('div');welcome.className='welcome-kicker';title.before(welcome)}if(welcome)welcome.innerHTML='<span class="welcome-hand">👋</span><div><b>BEM-VINDO, TRILHEIRO(A)!</b><small>Sua próxima aventura começa aqui.</small></div>';
}
const style=document.createElement('style');style.textContent=`
.hero-logo-wrap{width:170px!important;height:170px!important;margin:4px auto 14px!important;isolation:isolate}.hero-logo{width:154px!important;height:154px!important;object-fit:contain!important;border-radius:50%;opacity:0;transform:scale(.72) rotate(-7deg);animation:brandReveal .9s cubic-bezier(.2,.9,.25,1.15) .06s forwards,brandFloat 4.5s ease-in-out 1.1s infinite;filter:drop-shadow(0 16px 30px rgba(0,0,0,.52)) drop-shadow(0 0 22px rgba(241,198,111,.20))}.hero-ring{inset:1px!important;border:1px solid rgba(241,198,111,.62)!important;box-shadow:0 0 0 7px rgba(241,198,111,.035),0 0 48px rgba(241,198,111,.20)!important;animation:ringPulse 3.2s ease-in-out infinite}.welcome-kicker{position:relative;z-index:3;display:flex;align-items:center;justify-content:center;gap:10px;width:max-content;max-width:96%;margin:4px auto 10px;padding:9px 13px;border:1px solid rgba(241,198,111,.20);border-radius:999px;background:linear-gradient(135deg,rgba(241,198,111,.10),rgba(110,212,193,.06));opacity:0;animation:welcomeRise .65s ease .3s forwards}.welcome-hand{font-size:18px}.welcome-kicker b{display:block;font-size:9px;letter-spacing:.11em;color:#fff3cc}.welcome-kicker small{display:block;font-size:8px;color:#91a69e;margin-top:2px}.hero-title{font-size:clamp(40px,10.5vw,58px)!important;line-height:.93!important;letter-spacing:-.045em!important;margin:8px auto 13px!important}.hero-title span{background:linear-gradient(90deg,#fff0b2,#f1c66f,#dc9e44)!important;-webkit-background-clip:text!important;background-clip:text!important;color:transparent!important}
.tr-protect-btn{width:100%;min-height:54px;margin:8px 0 4px;border-radius:16px;border:1px solid rgba(110,212,193,.25);background:linear-gradient(135deg,rgba(110,212,193,.13),rgba(241,198,111,.08));color:#f7f1df;font-weight:900;font-size:11px}.tr-protect-btn small{display:block;margin-top:3px;color:#8da49d;font-size:8px;font-weight:700}.tr-protected{position:fixed;inset:0;z-index:2147483646;display:none;background:#000;color:#eaf3ef;touch-action:none;overscroll-behavior:none;user-select:none;-webkit-user-select:none}.tr-protected.show{display:block}.tr-protected-inner{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:space-between;padding:max(20px,env(safe-area-inset-top)) 20px max(22px,env(safe-area-inset-bottom));background:radial-gradient(circle at 50% 28%,rgba(35,90,76,.14),transparent 34%),#000}.tr-protected-top{text-align:center;opacity:.75}.tr-protected-top b{display:block;font-size:10px;letter-spacing:.18em;color:#9bcfc1}.tr-protected-top span{display:block;font-size:8px;color:#71837e;margin-top:4px}.tr-protected-center{text-align:center}.tr-protected-lock{font-size:28px;opacity:.72}.tr-protected-distance{font-size:clamp(72px,25vw,118px);font-weight:950;line-height:.88;letter-spacing:-.075em;color:#f7f1df;margin-top:18px}.tr-protected-unit{font-size:13px;font-weight:900;color:#d4ad62;margin-top:10px}.tr-protected-time{font-size:20px;font-weight:850;margin-top:22px;color:#b6c6c0}.tr-protected-status{margin-top:10px;font-size:9px;font-weight:850;color:#6ed4c1;letter-spacing:.08em}.tr-protected-bottom{width:min(440px,100%);text-align:center}.tr-protected-note{font-size:8px;line-height:1.5;color:#52625d;margin-bottom:14px}.tr-unlock{width:100%;height:58px;border-radius:999px;border:1px solid #ffffff13;background:#0d1513;color:#d8e4df;font-size:10px;font-weight:900;letter-spacing:.07em;position:relative;overflow:hidden}.tr-unlock:before{content:"";position:absolute;inset:0 auto 0 0;width:0;background:linear-gradient(90deg,rgba(110,212,193,.13),rgba(241,198,111,.15));transition:width 1.2s linear}.tr-unlock.holding:before{width:100%}.tr-protected-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#6ed4c1;margin-right:6px;box-shadow:0 0 10px rgba(110,212,193,.6)}
@keyframes brandReveal{to{opacity:1;transform:scale(1) rotate(0)}}@keyframes brandFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-6px)}}@keyframes ringPulse{0%,100%{transform:scale(1);opacity:.78}50%{transform:scale(1.045);opacity:1}}@keyframes welcomeRise{from{opacity:0;transform:translateY(9px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){.hero-logo,.hero-ring,.welcome-kicker{animation:none!important;opacity:1!important;transform:none!important}}
`;document.head.appendChild(style);
function activeState(){try{return JSON.parse(localStorage.getItem('trilheiros_active')||'null')}catch{return null}}
let protectedOn=false,localWake=null,refreshTimer=null,holdTimer=null;
async function keepAwake(){try{if('wakeLock'in navigator&&!localWake){localWake=await navigator.wakeLock.request('screen');localWake.addEventListener('release',()=>{localWake=null;if(protectedOn&&document.visibilityState==='visible')setTimeout(keepAwake,300)})}}catch{}}
try{navigator.storage?.persist?.()}catch{}
function addProtectedMode(){
  if($('#trProtectBtn')||!$('#trackView'))return;
  const btn=document.createElement('button');btn.id='trProtectBtn';btn.className='tr-protect-btn';btn.innerHTML='🌑 MODO TRILHA PROTEGIDO<small>Tela escura • evita toques • mantém GPS ativo</small>';
  const actions=$('.tracking-actions')||$('.controls');if(actions)actions.before(btn);else $('#trackView').appendChild(btn);
  const overlay=document.createElement('div');overlay.id='trProtected';overlay.className='tr-protected';overlay.innerHTML='<div class="tr-protected-inner"><div class="tr-protected-top"><b>TRILHEIROS GPS • MODO PROTEGIDO</b><span>GPS registrando • tela mantida ativa</span></div><div class="tr-protected-center"><div class="tr-protected-lock">🌑</div><div id="trProtectedDistance" class="tr-protected-distance">0,00</div><div class="tr-protected-unit">KM</div><div id="trProtectedTime" class="tr-protected-time">00:00:00</div><div id="trProtectedStatus" class="tr-protected-status"><span class="tr-protected-dot"></span>GPS ATIVO</div></div><div class="tr-protected-bottom"><div class="tr-protected-note">Guarde o celular no bolso com esta tela aberta. Não pressione o botão físico de bloquear: Android/iPhone podem suspender o navegador e interromper o GPS.</div><button id="trUnlock" class="tr-unlock">SEGURE 1,2s PARA VOLTAR</button></div></div>';document.body.appendChild(overlay);
  const update=()=>{const d=$('#distanceValue'),t=$('#timeValue'),g=$('#gpsBadge'),a=activeState();$('#trProtectedDistance').textContent=d?.textContent||((a?.distanceM||0)/1000).toFixed(2).replace('.',',');$('#trProtectedTime').textContent=t?.textContent||'00:00:00';$('#trProtectedStatus').innerHTML=`<span class="tr-protected-dot"></span>${(g?.textContent||'GPS ATIVO').toUpperCase()}`};
  const enter=async()=>{const a=activeState();if(!a?.active){window.toast?.('Inicie uma trilha antes de ativar este modo.');return}protectedOn=true;overlay.classList.add('show');document.documentElement.style.background='#000';await keepAwake();update();clearInterval(refreshTimer);refreshTimer=setInterval(update,1000)};
  const leave=()=>{protectedOn=false;overlay.classList.remove('show');clearInterval(refreshTimer);refreshTimer=null;localWake?.release?.().catch(()=>{});localWake=null};
  btn.onclick=enter;
  const unlock=$('#trUnlock');const begin=e=>{e.preventDefault();unlock.classList.add('holding');holdTimer=setTimeout(()=>{unlock.classList.remove('holding');leave()},1200)},cancel=()=>{clearTimeout(holdTimer);unlock.classList.remove('holding')};unlock.addEventListener('pointerdown',begin);unlock.addEventListener('pointerup',cancel);unlock.addEventListener('pointercancel',cancel);unlock.addEventListener('pointerleave',cancel);
  document.addEventListener('visibilitychange',()=>{if(protectedOn&&document.visibilityState==='visible')keepAwake()});window.addEventListener('pageshow',()=>{if(protectedOn)keepAwake()});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{applyBrand();addProtectedMode()},{once:true});else{applyBrand();addProtectedMode()}
window.addEventListener('load',()=>{applyBrand();addProtectedMode()},{once:true});
})();
