(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const LOGO='https://cdn.jsdelivr.net/gh/jonatasmarruda-prog/site@main/assets/logo-trilheiros.png';
const start=$('#startBtn'),install=$('#installBtn');if(!start||!install)return;

// Logo oficial: mesma fonte na interface e no card final.
$$('.brand-logo-mini,.hero-logo,.tracking-logo img,footer img').forEach(img=>{img.crossOrigin='anonymous';img.src=LOGO;});

// Abertura premium.
const title=$('.hero-title'),copy=$('.hero-copy');
if(title&&!$('.welcome-kicker')){const w=document.createElement('div');w.className='welcome-kicker';w.innerHTML='<span>👋</span><div><b>BEM-VINDO(A), TRILHEIRO(A)!</b><small>Sua próxima conquista começa aqui.</small></div>';title.before(w);title.innerHTML='Pra onde vamos<br><span>hoje?</span>';}
if(copy)copy.textContent='Escolha seu destino, confirme o GPS e comece a caminhar. O Trilheiros GPS registra distância, tempo, elevação e seu percurso para transformar a aventura em conquista.';
const home=$('#homeView'),hero=$('.hero-card');if(home&&hero)home.insertBefore(install,hero);

const css=document.createElement('style');css.textContent=`
.hero-logo-wrap{width:166px!important;height:166px!important;margin:4px auto 16px!important}.hero-logo{width:150px!important;height:150px!important;border-radius:50%;object-fit:contain;opacity:0;transform:scale(.72) rotate(-7deg);animation:logoIn .9s cubic-bezier(.2,.9,.25,1.15) .08s forwards,floatLogo 4.2s ease-in-out 1.1s infinite;filter:drop-shadow(0 15px 30px #0009) drop-shadow(0 0 22px #f1c66f33)}.hero-ring{inset:1px!important;border-color:#f1c66f99!important;box-shadow:0 0 0 7px #f1c66f0a,0 0 48px #f1c66f30!important;animation:ringPulse 3s ease-in-out infinite}.hero-logo-wrap:after{content:"";position:absolute;inset:-13px;border-radius:50%;background:conic-gradient(from 210deg,transparent 0 67%,#ffe8a755 74%,transparent 82%);animation:spin 8s linear infinite;pointer-events:none;z-index:-1}.welcome-kicker{position:relative;z-index:2;display:flex;align-items:center;justify-content:center;gap:10px;width:max-content;max-width:96%;margin:2px auto 10px;padding:9px 13px;border:1px solid #f1c66f29;border-radius:999px;background:linear-gradient(135deg,#f1c66f12,#6ed4c10d);opacity:0;animation:rise .65s ease .35s forwards}.welcome-kicker>span{font-size:18px;animation:wave 2.5s ease-in-out 1s infinite;transform-origin:70% 70%}.welcome-kicker b{display:block;color:#fff3cb;font-size:9px;letter-spacing:.11em}.welcome-kicker small{display:block;color:#91a69e;font-size:8px;margin-top:2px}.hero-title{font-size:clamp(39px,10vw,56px)!important;line-height:.94!important;margin-top:8px!important}.hero-copy{font-size:12px!important;max-width:455px!important}.install-card{display:flex!important;margin:0 0 12px!important;position:relative;overflow:hidden;border-color:#f1c66f45!important;background:linear-gradient(125deg,#2eb97b22,#f1c66f12)!important}.install-card:before{content:"";position:absolute;top:0;left:-55%;width:36%;height:100%;background:linear-gradient(90deg,transparent,#ffffff19,transparent);transform:skewX(-18deg);animation:shine 4.8s ease-in-out infinite}.install-card.installed{border-color:#46da9447!important;background:#46da9414!important}
.tr-modal{position:fixed;inset:0;z-index:9999;background:#000c;backdrop-filter:blur(11px);display:none;align-items:flex-end;justify-content:center;padding:14px}.tr-modal.show{display:flex}.tr-sheet{width:min(560px,100%);background:linear-gradient(160deg,#10372f,#061b17);border:1px solid #f1c66f40;border-radius:28px;padding:18px;color:#f7f1df;box-shadow:0 35px 90px #000a}.tr-handle{width:44px;height:4px;border-radius:99px;background:#ffffff22;margin:0 auto 14px}.tr-icon{font-size:36px}.tr-sheet h3{font-size:22px;margin:8px 0 6px}.tr-sheet>p{color:#9fb0ab;font-size:12px;line-height:1.5;margin:0}.tr-steps{display:grid;gap:8px;margin:14px 0}.tr-step{display:flex;gap:10px;padding:11px;border-radius:14px;background:#ffffff09;border:1px solid #ffffff0d}.tr-num{width:27px;height:27px;border-radius:9px;display:grid;place-items:center;background:#f1c66f18;color:#f1c66f;font-size:10px;font-weight:900;flex:none}.tr-step b{display:block;font-size:11px}.tr-step span{display:block;color:#879b95;font-size:9px;margin-top:2px;line-height:1.4}.tr-close{width:100%;height:50px;border:1px solid #ffffff12;border-radius:15px;background:#14382f;color:#fff;font-weight:900}
@keyframes logoIn{to{opacity:1;transform:scale(1) rotate(0)}}@keyframes floatLogo{0%,100%{transform:translateY(0)}50%{transform:translateY(-6px)}}@keyframes ringPulse{0%,100%{transform:scale(1);opacity:.78}50%{transform:scale(1.045);opacity:1}}@keyframes spin{to{transform:rotate(360deg)}}@keyframes rise{to{opacity:1;transform:none}}@keyframes wave{0%,70%,100%{transform:rotate(0)}76%{transform:rotate(18deg)}82%{transform:rotate(-8deg)}88%{transform:rotate(12deg)}}@keyframes shine{0%,64%{left:-55%}82%,100%{left:125%}}
@media(prefers-reduced-motion:reduce){.hero-logo,.hero-ring,.hero-logo-wrap:after,.welcome-kicker,.welcome-kicker>span,.install-card:before{animation:none!important;opacity:1!important;transform:none!important}}
`;document.head.appendChild(css);

// Modal de orientação.
const modal=document.createElement('div');modal.className='tr-modal';modal.innerHTML='<div class="tr-sheet"><div class="tr-handle"></div><div class="tr-icon">📲</div><h3></h3><p></p><div class="tr-steps"></div><button class="tr-close">ENTENDI</button></div>';document.body.appendChild(modal);
const open=(ic,t,txt,steps=[])=>{modal.querySelector('.tr-icon').textContent=ic;modal.querySelector('h3').textContent=t;modal.querySelector('p').textContent=txt;modal.querySelector('.tr-steps').innerHTML=steps.map((s,i)=>`<div class="tr-step"><span class="tr-num">${i+1}</span><div><b>${s[0]}</b><span>${s[1]}</span></div></div>`).join('');modal.classList.add('show')};const close=()=>modal.classList.remove('show');modal.querySelector('.tr-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};

// Instalação PWA.
const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
const installed=()=>{if(standalone()){install.classList.add('installed');install.querySelector('.install-icon').textContent='✓';install.querySelector('strong').textContent='TRILHEIROS GPS INSTALADO';install.querySelector('span').textContent='Você já está usando como aplicativo';install.querySelector('.install-arrow').textContent='';}};installed();addEventListener('appinstalled',installed);
install.addEventListener('click',()=>{if(standalone())return;setTimeout(()=>{if(typeof deferredInstall!=='undefined'&&deferredInstall)return;const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);if(ios)open('📱','Instalar no iPhone','Use o Safari para colocar o Trilheiros GPS na tela inicial.',[['Abra no Safari','Se estiver dentro de outro aplicativo, escolha Abrir no Safari.'],['Compartilhar','Toque no quadrado com a seta para cima.'],['Adicionar à Tela de Início','Confirme em Adicionar.']]);else open('📲','Instalar no Android','Abra este link no Google Chrome para instalar.',[['Abrir no Chrome','No WhatsApp, ChatGPT ou Instagram, toque em ⋮ e escolha Abrir no Chrome.'],['Menu ⋮','No Chrome, abra o menu no canto superior direito.'],['Instalar app','Pode aparecer como Adicionar à tela inicial.']]);},120)});

// Pré-teste de GPS.
let allow=false;const getPos=o=>new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,o));
async function preflight(){if(!isSecureContext||!navigator.geolocation)throw{code:'unsupported'};try{if(navigator.permissions?.query){const p=await navigator.permissions.query({name:'geolocation'});if(p.state==='denied')throw{code:1}}}catch(e){if(e?.code===1)throw e}try{return await getPos({enableHighAccuracy:true,maximumAge:0,timeout:18000})}catch(e){if(e.code===1)throw e;return getPos({enableHighAccuracy:false,maximumAge:30000,timeout:10000})}}
const gpsErr=e=>{if(e?.code===1)return open('🔒','Permita a localização','O Trilheiros GPS precisa da localização para medir a trilha.',[['Permissões do site','No Chrome, abra as permissões do site.'],['Localização','Escolha Permitir e ative localização precisa.'],['Tentar novamente','Volte e toque em Iniciar Trilha.']]);if(e?.code===2)return open('🛰️','GPS sem posição','O celular ainda não conseguiu determinar sua localização.',[['Ative a Localização','Confira o GPS nas configurações rápidas.'],['Área aberta','Fique alguns segundos longe de paredes/telhados.'],['Tentar novamente','Inicie novamente.']]);if(e?.code===3)return open('⏱️','GPS demorou para responder','O primeiro sinal pode levar alguns segundos.',[['Localização precisa','Autorize quando o Android perguntar.'],['Área aberta','Aguarde e tente novamente.']]);open('🛰️','Não foi possível acessar o GPS','Abra no Google Chrome e confirme que a localização está ligada.',[['Abrir no Chrome','Navegadores internos podem limitar o GPS.'],['Permitir localização','Autorize o acesso ao GPS.']])};
start.addEventListener('click',async e=>{if(allow){allow=false;return}e.preventDefault();e.stopImmediatePropagation();if(start.disabled)return;const ic=start.querySelector('.start-icon'),t=start.querySelector('strong'),sub=start.querySelector('small');start.disabled=true;ic.textContent='🛰️';t.textContent='CONFIRMANDO GPS...';sub.textContent='Aguarde alguns segundos';try{await preflight();allow=true;start.disabled=false;ic.textContent='🥾';t.textContent='INICIAR TRILHA';sub.textContent='GPS confirmado — iniciando';start.click();setTimeout(()=>sub.textContent='Primeiro confirmamos o GPS do seu celular',1200)}catch(err){start.disabled=false;ic.textContent='🥾';t.textContent='INICIAR TRILHA';sub.textContent='Primeiro confirmamos o GPS do seu celular';gpsErr(err)}},true);

// Reforça a logo no card final.
const cardLogo=new Image();cardLogo.crossOrigin='anonymous';cardLogo.src=LOGO;const gen=$('#generateBtn');if(gen)gen.addEventListener('click',()=>setTimeout(()=>{const c=$('#artCanvas');if(!c||!cardLogo.complete)return;const x=c.getContext('2d'),s=Math.round(Math.min(c.width,c.height)*.18),p=Math.round(c.width*.045);x.save();x.shadowColor='#0008';x.shadowBlur=24;x.drawImage(cardLogo,p,p,s,s);x.restore()},150));
})();
