import type { Context, Config } from "@netlify/functions";
import { getDeployStore, getStore } from "@netlify/blobs";
const PROF=["porra","caralho","merda","bosta","puta","puto","fdp","foda","foder","cacete","desgraca","vai tomar no cu","tomar no cu","cuzao","arrombado","idiota","imbecil","burro","otario","babaca","vagabundo","vagabunda"];
const NEG=["nao gostei","nao recomendo","nunca mais","foi pessimo","foi horrivel","muito ruim","horrivel","pessimo","terrivel","decepcao","decepcionante","mal organizado","desorganizado","bagunca","lixo","ridiculo","vergonha","absurdo","enganacao","fraude","golpe","atendimento ruim","organizacao ruim","nao vale","arrependi","arrependimento","odiei","detestei"];
const norm=(t="")=>t.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[0@]/g,"o").replace(/[1!]/g,"i").replace(/3/g,"e").replace(/4/g,"a").replace(/[5$]/g,"s").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
function moderate(t:string){const n=norm(t);if(PROF.some(x=>n.includes(norm(x))))return"A mensagem contém linguagem ofensiva. Ajuste o texto para publicar na galeria.";if(NEG.some(x=>n.includes(norm(x))))return"A mensagem foi identificada como negativa ou depreciativa. Conte sua experiência de forma respeitosa e positiva para publicar.";if(/\b(eles|voces|organizador|guia|grupo)\b.{0,30}\b(ruim|pessim|horrivel|incompetente|desorganizado|ridiculo)\b/i.test(n)||/\b(reclamo|reclamacao)\b/i.test(n))return"A mensagem parece conter ataque ou reclamação. Reescreva de forma respeitosa e positiva para compartilhar.";return""}
function store(name:string){const c=(globalThis as any).Netlify?.context?.deploy?.context;return c==="production"?getStore(name,{consistency:"strong"}):getDeployStore(name)}
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function clean(v:FormDataEntryValue|null,max:number){return String(v??"").trim().replace(/\s+/g," ").slice(0,max)}
export default async(req:Request,context:Context)=>{const posts=store("trilheiros-gallery-posts");if(req.method==="GET"){const {blobs}=await posts.list({prefix:"post-"});const latest=blobs.sort((a,b)=>b.key.localeCompare(a.key)).slice(0,80);const values=await Promise.all(latest.map(i=>posts.get(i.key,{type:"json"})));return json({posts:values.filter(Boolean)})}if(req.method!=="POST")return json({message:"Método não permitido."},405);const form=await req.formData();if(clean(form.get("website"),200))return json({message:"Publicação recusada."},400);const name=clean(form.get("name"),50),trip=clean(form.get("trip"),70),description=clean(form.get("description"),360),caption=clean(form.get("caption"),600),photo=form.get("photo");if(!name||!trip||!description)return json({message:"Preencha nome, passeio e descrição."},400);if(!(photo instanceof File)||!photo.type.startsWith("image/"))return json({message:"Envie uma foto válida."},400);if(photo.size>5*1024*1024)return json({message:"A foto ficou muito grande. Escolha outra imagem."},413);const blocked=moderate([name,trip,description,caption].join(" "));if(blocked)return json({code:"moderation",message:blocked},422);const id=crypto.randomUUID(),createdAt=new Date().toISOString(),photoKey=`photo-${id}.jpg`,media=store("trilheiros-gallery-media");await media.set(photoKey,await photo.arrayBuffer());const post={id,name,trip,description,caption,photoKey,createdAt};const sortable=createdAt.replace(/\D/g,"").slice(0,17);await posts.setJSON(`post-${sortable}-${id}`,post);return json({ok:true,post},201)};
export const config:Config={path:"/api/posts"};
