const $=s=>document.querySelector(s);const state={blob:null,url:'',posts:[],captionIndex:0};
const PROF=['porra','caralho','merda','bosta','puta','puto','fdp','foda','foder','cacete','desgraca','vai tomar no cu','tomar no cu','cuzao','arrombado','idiota','imbecil','burro','otario','babaca','vagabundo','vagabunda'];
const NEG=['nao gostei','nao recomendo','nunca mais','foi pessimo','foi horrivel','muito ruim','horrivel','pessimo','terrivel','decepcao','decepcionante','mal organizado','desorganizado','bagunca','lixo','ridiculo','vergonha','absurdo','enganacao','fraude','golpe','atendimento ruim','organizacao ruim','nao vale','arrependi','arrependimento','odiei','detestei'];
const norm=t=>(t||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[0@]/g,'o').replace(/[1!]/g,'i').replace(/3/g,'e').replace(/4/g,'a').replace(/[5$]/g,'s').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
function moderate(t){const n=norm(t);if(PROF.some(x=>n.includes(norm(x))))return{ok:false,msg:'A mensagem contém linguagem ofensiva. Ajuste o texto para publicar na galeria.'};if(NEG.some(x=>n.includes(norm(x))))return{ok:false,msg:'A mensagem foi identificada como negativa ou depreciativa. Conte sua experiência de forma respeitosa e positiva para publicar.'};if(/\b(eles|voces|organizador|guia|grupo)\b.{0,30}\b(ruim|pessim|horrivel|incompetente|desorganizado|ridiculo)\b/i.test(n)||/\b(reclamo|reclamacao)\b/i.test(n))return{ok:false,msg:'A mensagem parece conter ataque ou reclamação. Reescreva de forma respeitosa e positiva para compartilhar.'};return{ok:true}}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2100)}function msg(t,type){const e=$('#formMessage');e.hidden=false;e.className='msg '+type;e.textContent=t}function clearMsg(){$('#formMessage').hidden=true}function trip(){return $('#trip').value==='Outro'?$('#customTrip').value.trim():$('#trip').value}
function updateMod(){const r=moderate([$('#name').value,trip(),$('#description').value,$('#caption').value].join(' ')),e=$('#modStatus');e.className='mod'+(r.ok?'':' bad');e.textContent=r.ok?'✓ Linguagem adequada para a galeria.':'⚠ '+r.msg}
$('#trip').onchange=()=>{$('#customWrap').hidden=$('#trip').value!=='Outro';updateMod()};$('#description').oninput=()=>{$('#count').textContent=$('#description').value.length+'/360';updateMod()};['name','customTrip','caption'].forEach(id=>$('#'+id).addEventListener('input',updateMod));
async function imageObj(file){if(/heic|heif/i.test(file.type)||/\.(heic|heif)$/i.test(file.name)){if(!window.heic2any)throw Error();const c=await heic2any({blob:file,toType:'image/jpeg',quality:.9});file=Array.isArray(c)?c[0]:c}if('createImageBitmap'in window){try{return await createImageBitmap(file,{imageOrientation:'from-image'})}catch{}}const u=URL.createObjectURL(file),im=await new Promise((res,rej)=>{const i=new Image;i.onload=()=>res(i);i.onerror=rej;i.src=u});URL.revokeObjectURL(u);return im}
async function prepare(file){if(!file)throw Error();const im=await imageObj(file),max=1800,r=Math.min(1,max/Math.max(im.width,im.height)),w=Math.round(im.width*r),h=Math.round(im.height*r),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,w,h);x.drawImage(im,0,0,w,h);if(im.close)try{im.close()}catch{};return await new Promise(res=>c.toBlob(res,'image/jpeg',.86))}
$('#photo').onchange=async e=>{clearMsg();try{$('#uploadEmpty').innerHTML='<div class="ico">⏳</div><b>Preparando sua foto...</b><span>Aguarde um instante</span>';state.blob=await prepare(e.target.files[0]);if(state.url)URL.revokeObjectURL(state.url);state.url=URL.createObjectURL(state.blob);$('#photoPreview').src=state.url;$('#photoPreview').hidden=false;$('#uploadEmpty').hidden=true;$('#changePhoto').hidden=false;toast('Foto pronta 📸')}catch{$('#uploadEmpty').hidden=false;$('#uploadEmpty').innerHTML='<div class="ico">📷</div><b>Toque para escolher sua foto</b><span>JPG, PNG, WEBP, HEIC e formatos comuns do celular</span>';msg('Não consegui abrir essa foto. Escolha outra imagem do celular.','error')}};$('#changePhoto').onclick=e=>{e.preventDefault();$('#photo').click()};
function caption(){const n=$('#name').value.trim()||'Mais um trilheiro',t=trip()||'essa aventura',d=$('#description').value.trim(),arr=[`🌿✨ ${n} viveu uma experiência especial em ${t} com os Trilheiros de Rondonópolis! ${d?d+' ':''}Mais uma história para guardar na memória. 🥾💚\n\n#TrilheirosDeRondonopolis #Natureza #Aventura`,`🥾💚 Mais uma aventura vivida! ${n} esteve em ${t} e compartilhou esse momento com a nossa galera. ${d?d+' ':''}Porque cada trilha deixa uma lembrança diferente. 🌄✨\n\n@trilheiros.roomt`,`📸 Uma foto que conta uma história: ${n} em ${t}. ${d?d+' ':''}Natureza, boas companhias e experiências que ficam para sempre. 🌿🏞️\n\nTrilheiros de Rondonópolis • Aqui ninguém vai só.`];$('#caption').value=arr[state.captionIndex++%arr.length].slice(0,600);updateMod()}$('#generateCaption').onclick=caption;
$('#postForm').onsubmit=async e=>{e.preventDefault();clearMsg();let n=$('#name').value.trim(),t=trip(),d=$('#description').value.trim(),c=$('#caption').value.trim();if(!state.blob)return msg('Escolha uma foto para publicar.','error');if(!n||!t||!d)return msg('Preencha seu nome, passeio e descrição.','error');if(!$('#consent').checked)return msg('Confirme a autorização para exibir a foto.','error');if(!c){caption();c=$('#caption').value.trim()}const m=moderate([n,t,d,c].join(' '));if(!m.ok)return msg(m.msg,'error');const b=$('#publishBtn');b.disabled=true;b.querySelector('span').textContent='PUBLICANDO...';try{const f=new FormData;f.append('name',n);f.append('trip',t);f.append('description',d);f.append('caption',c);f.append('website',$('#website').value);f.append('photo',state.blob,'foto.jpg');const r=await fetch('/api/posts',{method:'POST',body:f}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.message||'Não foi possível publicar agora.');msg('Experiência publicada com sucesso! 💚 Ela já está na galeria.','success');toast('Publicado na galeria ✨');e.target.reset();$('#customWrap').hidden=true;$('#photoPreview').hidden=true;$('#changePhoto').hidden=true;$('#uploadEmpty').hidden=false;$('#uploadEmpty').innerHTML='<div class="ico">📷</div><b>Toque para escolher sua foto</b><span>JPG, PNG, WEBP, HEIC e formatos comuns do celular</span>';$('#count').textContent='0/360';if(state.url)URL.revokeObjectURL(state.url);state.blob=null;state.url='';await load();location.hash='#galeria'}catch(er){msg(er.message||'Não foi possível publicar agora.','error')}finally{b.disabled=false;b.querySelector('span').textContent='PUBLICAR EXPERIÊNCIA'}};
const esc=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function date(s){try{return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s))}catch{return''}}
function filters(){const a=[...new Set(state.posts.map(p=>p.trip))].sort((a,b)=>a.localeCompare(b,'pt-BR')),sel=$('#filterTrip'),v=sel.value;sel.innerHTML='<option value="">Todos os passeios</option>'+a.map(t=>`<option>${esc(t)}</option>`).join('');if(a.includes(v))sel.value=v;$('#postCount').textContent=state.posts.length;$('#tripCount').textContent=a.length}
function render(){const q=norm($('#search').value),f=$('#filterTrip').value,a=state.posts.filter(p=>(!q||norm(p.name+' '+p.trip+' '+p.description).includes(q))&&(!f||p.trip===f)),g=$('#galleryGrid');g.innerHTML='';$('#emptyState').hidden=!!a.length;a.forEach(p=>{const c=document.createElement('article');c.className='card';c.innerHTML=`<div class="photo"><img loading="lazy" src="/api/photo?id=${encodeURIComponent(p.photoKey)}" alt="Foto de ${esc(p.name)}"><span class="tag">${esc(p.trip)}</span></div><div class="cardBody"><div class="meta"><span class="author">${esc(p.name)}</span><span class="date">${date(p.createdAt)}</span></div><p class="desc">${esc(p.description)}</p>${p.caption?`<div class="caption">${esc(p.caption).replace(/\n/g,'<br>')}</div>`:''}<div class="cardActions"><span class="badge">✓ experiência compartilhada</span><button class="share" type="button">↗ Compartilhar</button></div></div>`;c.querySelector('.share').onclick=()=>sharePost(p);g.appendChild(c)})}
async function sharePost(p){const text=p.caption||`🌿 ${p.name} compartilhou sua experiência em ${p.trip} com os Trilheiros de Rondonópolis.`;try{const r=await fetch('/api/photo?id='+encodeURIComponent(p.photoKey)),blob=await r.blob(),file=new File([blob],'experiencia-trilheiros.jpg',{type:'image/jpeg'});if(navigator.canShare?.({files:[file]})){await navigator.share({title:p.trip+' • Trilheiros',text,files:[file]});return}}catch{}if(navigator.share)await navigator.share({title:p.trip+' • Trilheiros',text,url:location.href});else{await navigator.clipboard.writeText(text+'\n'+location.href);toast('Legenda copiada ✨')}}
async function load(){const g=$('#galleryGrid');g.innerHTML='<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>';$('#emptyState').hidden=true;try{const r=await fetch('/api/posts',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();state.posts=Array.isArray(d.posts)?d.posts:[];filters();render()}catch{g.innerHTML='';$('#emptyState').hidden=false;$('#emptyState').querySelector('h3').textContent='A galeria está sendo preparada.';$('#emptyState').querySelector('p').textContent='Recarregue a página em alguns instantes.'}}
$('#search').oninput=render;$('#filterTrip').onchange=render;$('#refreshBtn').onclick=load;updateMod();load();
